# Checkout
CHECKOUT_CLOSED = 2
CHECKOUT_PICKUP_AND_SIGNED = 1
CHECKOUT_CREATED = 0
CHECKOUT_PICKUP_REJECT = -1
CHECKOUT_SUBMIT = -2
CHECKOUT_DRAFT = -3
CHECKOUT_STATUS_CHOICES = (
    (CHECKOUT_DRAFT, 'Draft'),
    (CHECKOUT_SUBMIT, 'Submitted'),
    (CHECKOUT_CREATED, 'Checkout Created'),
    (CHECKOUT_PICKUP_AND_SIGNED, 'Picked up and Signed'),
    (CHECKOUT_CLOSED, 'Closed'),
)
# Checkout Request
CHECKOUT_REQUEST_DRAFT = CHECKOUT_DRAFT
CHECKOUT_REQUEST_SUBMIT = CHECKOUT_SUBMIT
CHECKOUT_REQUEST_RETURNED = -4
CHECKOUT_REQUEST_STATUS_CHOICES = (
    (CHECKOUT_REQUEST_DRAFT, 'Request Draft'),
    (CHECKOUT_REQUEST_SUBMIT, 'Request Submitted'),
    (CHECKOUT_REQUEST_RETURNED, 'Request Returned'),
    (CHECKOUT_CREATED, 'Checkout Created'),
    (CHECKOUT_PICKUP_AND_SIGNED, 'Picked up and Signed'),
    (CHECKOUT_CLOSED, 'Closed'),
)

PICKUP_OPTIONS = (
    (CHECKOUT_PICKUP_AND_SIGNED, "Signed"),
    (CHECKOUT_PICKUP_REJECT, "Reject"),
)

# Checkin
CHECKIN_ACCOUNTING_APPROVED = 4
CHECKIN_MGR_APPROVED = 3
CHECKIN_FORCE_CHECKIN = 2
CHECKIN_CHECKED_IN = 1
CHECKIN_PENDING_MGR_REVIEW = -1
CHECKIN_PENDING_ACCOUNTING_REVIEW = -2
CHECKIN_REJECT = 0
CHECKIN_STATUS_CHOICES = (
    (CHECKIN_ACCOUNTING_APPROVED, 'Accounting Approved'),
    (CHECKIN_PENDING_ACCOUNTING_REVIEW, 'Pending Accounting Review'),
    (CHECKIN_MGR_APPROVED, 'Inventory Manager Approved'),
    (CHECKIN_PENDING_MGR_REVIEW, 'Pending Inventory Manager Review'),
    (CHECKIN_CHECKED_IN, 'Normal Checkin'),
    (CHECKIN_FORCE_CHECKIN, 'Force Checkin'),
    (CHECKIN_REJECT, 'Reject'),
)

# COMMON
REVIEW_RESULT_APPROVE = 1
REVIEW_RESULT_PENDING = 0
REVIEW_RESULT_ESCALATE = -1
REVIEW_RESULT_REJECT = -2
REVIEW_CHOICES = (
    (REVIEW_RESULT_APPROVE, 'Approve'),
    (REVIEW_RESULT_PENDING, 'Pending Review'),
    (REVIEW_RESULT_ESCALATE, 'Escalated, Pending Review'),
    (REVIEW_RESULT_REJECT, 'Reject'),
)
