# Generated by Django 2.2.12 on 2020-06-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='object_sid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sam_account_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
