# Generated by Django 3.0.11 on 2020-11-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusIDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.SmallIntegerField(blank=True, db_column='StatusID', null=True)),
                ('status_name', models.CharField(blank=True, db_column='StatusName', max_length=30, null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'BookingStatusIDInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentIDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, db_column='DeptName', max_length=30, null=True)),
                ('created_by_id', models.CharField(blank=True, db_column='CreatedByID', max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_by_id', models.CharField(blank=True, db_column='UpdatedByID', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('original_dept_id', models.IntegerField(db_column='OriginalDeptID')),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'DepartmentIDInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuelTypeIDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(blank=True, db_column='FuelName', max_length=30, null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'FuelTypeIDInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infringement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infringement_number', models.CharField(db_column='InfringementNumber', max_length=30)),
                ('plate_number', models.CharField(db_column='PlateNumber', max_length=30)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('user_id', models.CharField(blank=True, db_column='UserID', max_length=32, null=True)),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
                ('paid_date', models.DateTimeField(blank=True, db_column='PaidDate', null=True)),
                ('created_by_id', models.CharField(blank=True, db_column='CreatedByID', max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_by_id', models.CharField(blank=True, db_column='UpdatedByID', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('original_id', models.IntegerField(blank=True, db_column='OriginalID', null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'Infringement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobIDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_abbreviation', models.CharField(blank=True, db_column='JobAbbreviation', max_length=30, null=True)),
                ('job_name', models.CharField(blank=True, db_column='JobName', max_length=30, null=True)),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
                ('created_by_id', models.CharField(blank=True, db_column='CreatedByID', max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_by_id', models.CharField(blank=True, db_column='UpdatedByID', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('original_job_code_id', models.IntegerField(blank=True, db_column='OriginalJobCodeID', null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'JobIDInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, db_column='SN', max_length=25, null=True)),
                ('plate_number', models.CharField(db_column='PlateNumber', max_length=30)),
                ('service_name', models.CharField(blank=True, db_column='ServiceName', max_length=600, null=True)),
                ('workshop_id', models.CharField(blank=True, db_column='WorkshopID', max_length=32, null=True)),
                ('service_price', models.FloatField(blank=True, db_column='ServicePrice', null=True)),
                ('start_date', models.DateTimeField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('created_by_id', models.CharField(blank=True, db_column='CreatedByID', max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_by_id', models.CharField(blank=True, db_column='UpdatedByID', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('original_id', models.IntegerField(blank=True, db_column='OriginalID', null=True)),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'ServiceForm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissionTypeIDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_type', models.CharField(blank=True, db_column='TransmissionType', max_length=30, null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'TransmissionTypeIDInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, db_column='SN', max_length=26, null=True)),
                ('booking_start_at', models.DateTimeField(blank=True, db_column='BookingStartAt', null=True)),
                ('booking_end_at', models.DateTimeField(blank=True, db_column='BookingEndAt', null=True)),
                ('department_id', models.CharField(blank=True, db_column='DepartmentID', max_length=50, null=True)),
                ('job_code_id', models.IntegerField(blank=True, db_column='JobCodeID', null=True)),
                ('user_id', models.CharField(blank=True, db_column='UserID', max_length=32, null=True)),
                ('vehicle_id', models.CharField(blank=True, db_column='VehicleID', max_length=32, null=True)),
                ('booking_reason', models.CharField(blank=True, db_column='BookingReason', max_length=1200, null=True)),
                ('booking_notes', models.CharField(blank=True, db_column='BookingNotes', max_length=1200, null=True)),
                ('admin_notes', models.CharField(blank=True, db_column='AdminNotes', max_length=1200, null=True)),
                ('maintenance_booking', models.CharField(blank=True, db_column='MaintenanceBooking', max_length=1200, null=True)),
                ('started_mileage', models.FloatField(blank=True, db_column='StartedMileage', null=True)),
                ('returned_mileage', models.FloatField(blank=True, db_column='ReturnedMileage', null=True)),
                ('returned_date', models.DateTimeField(blank=True, db_column='ReturnedDate', null=True)),
                ('return_note', models.CharField(blank=True, db_column='ReturnNote', max_length=1200, null=True)),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
                ('clean', models.SmallIntegerField(blank=True, db_column='Clean', null=True)),
                ('damage_info', models.CharField(blank=True, db_column='DamageInfo', max_length=1200, null=True)),
                ('created_by_id', models.CharField(blank=True, db_column='CreatedByID', max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_by_id', models.CharField(blank=True, db_column='UpdatedByID', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('original_id', models.IntegerField(blank=True, db_column='OriginalID', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=200, null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'VehicleBooking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(db_column='VehicleID', max_length=50)),
                ('plate_number', models.CharField(db_column='PlateNumber', max_length=30)),
                ('last_known_odo', models.FloatField(blank=True, db_column='LastKnownOdo', null=True)),
                ('last_odo', models.FloatField(blank=True, db_column='LastOdo', null=True)),
                ('mfg_date', models.IntegerField(blank=True, db_column='MFGDate', null=True)),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=30, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=30, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=30, null=True)),
                ('transmission_type_id', models.SmallIntegerField(blank=True, db_column='TransmissionTypeID', null=True)),
                ('vehicle_type_id', models.IntegerField(blank=True, db_column='VehicleTypeID', null=True)),
                ('available_km', models.CharField(blank=True, db_column='AvailableKm', max_length=50, null=True)),
                ('department_id', models.CharField(blank=True, db_column='DepartmentID', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=32, null=True)),
                ('fuel_type_id', models.SmallIntegerField(blank=True, db_column='FuelTypeID', null=True)),
                ('wof_exp_date', models.DateTimeField(blank=True, db_column='WoFExpDate', null=True)),
                ('rego_exp_date', models.DateTimeField(blank=True, db_column='RegoExpDate', null=True)),
                ('created_by_id', models.CharField(blank=True, db_column='CreatedByID', max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_by_id', models.CharField(blank=True, db_column='UpdatedByID', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('original_id', models.IntegerField(blank=True, db_column='OriginalID', null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'VehicleInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleTypeIDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type_name', models.CharField(blank=True, db_column='VehicleTypename', max_length=30, null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'VehicleTypeIDInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkshopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.CharField(db_column='WorkshopID', max_length=50)),
                ('workshop_name', models.CharField(db_column='WorkshopName', max_length=60)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=600, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='ContactPerson', max_length=30, null=True)),
                ('contact_phone', models.CharField(blank=True, db_column='ContactPhone', max_length=60, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=60, null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=1200, null=True)),
                ('created_by_id', models.CharField(blank=True, db_column='CreatedByID', max_length=32, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updated_by_id', models.CharField(blank=True, db_column='UpdatedByID', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('original_id', models.IntegerField(blank=True, db_column='OriginalID', null=True)),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
                ('cdate', models.DateTimeField(blank=True, db_column='Cdate', null=True)),
            ],
            options={
                'db_table': 'WorkshopInfo',
                'managed': False,
            },
        ),
    ]
