# Generated by Django 3.0.11 on 2020-12-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infringement',
            options={'managed': False, 'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='jobidinfo',
            options={'managed': False, 'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='serviceform',
            options={'managed': False, 'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False, 'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='vehiclebooking',
            options={'managed': False, 'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='vehicleinfo',
            options={'managed': False, 'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='workshopinfo',
            options={'managed': False, 'ordering': ('-id',)},
        ),
    ]
